using AutoMapper;
using Bill_system_API.DTOs;
using Bill_system_API.Models;

namespace Bill_system_API.MappinigProfiles
{
    public class ItemProfile: Profile
    {
        public ItemProfile()
        {
            //CreateMap<ItemDto, Item>()
            //.ForMember(dest => dest.Id, opt => opt.Ignore()); // Ignore Id if it's generated by the database
       


           

            CreateMap<Item, ItemDto>().ReverseMap();
        }
    }
}
